{% set name = "djangocms-picture" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangocms-picture-{{ version }}.tar.gz
  sha256: 29ffadc514bfa306ec1f2ebb145391b9b860c12ba001e2475dffb5fe1be5cac2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django-cms >=3.7
    - django-filer >=1.7
    - djangocms-attributes-field >=1
    - easy-thumbnails

test:
  imports:
    - djangocms_picture
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-cms/djangocms-picture
  summary: Adds an image plugin to django CMS
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
